import = [  
    "~/.config/alacritty/themes/themes/dracula_plus.toml.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
opacity=0.9

decorations = "Buttonless"

[font]
size = 14
normal.family= "JetBrains Mono" 

#for video
# size = 35.0
